name: Delete Branches

on:
 workflow_dispatch:
  # schedule:
  #   - cron:  '0 0 * * *' # run daily at midnight

jobs:
  delete_branches:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
      
    - name: Delete remote branches
      run: |
        # Get all remote branches
        branches=`git branch -r | grep -v HEAD`

        # Loop through each branch
        for branch in $branches; do
          # Delete the branch from remote
          git push origin --delete ${branch#origin/}
        done
