name: Build Docker Image

on:
 workflow_dispatch:
    # branches:
      # - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        # Login to Docker Hub
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        # Build the Docker image
        docker build -t <image_name>:<tag> .

        # Push the Docker image to Docker Hub
        docker push <image_name>:<tag>
